version: "3.1"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "spring"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword" ]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_springboot
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic123
          - xpack.security.transport.ssl.enabled=true
    #      - bootstrap.memory_lock=true
    #      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elasticsearch.keystore
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana_springboot
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      #Needed to create a token in http://localhost:9200/_security/service/elastic/kibana/credential/token/token1?pretty with basic auth with elastic user
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpVWWdkYjB4M1JvV0lOTERULXcyT0d3
    #      ELASTICSEARCH_USERNAME: elastic
    #      ELASTICSEARCH_PASSWORD: elastic123
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash_springboot
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic123
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: elastic123
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  fleet-server:
    hostname: fleet-server
    image: docker.elastic.co/beats/elastic-agent:8.3.3
    container_name: fleet-server
    #    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    ports:
      - "8220:8220"
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elastic
    environment:
      - FLEET_ENROLLMENT_TOKEN=eGFtclk1QUJCMUljb3RCN2p5MjA6VDVkeWxaRG1UQUNDWV9pWmllUU5BZw==
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_PORT=8220
      - FLEET_SERVER_HOST=0.0.0.0
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MTk3MzQ5MTExMTQ6aUwzdDVMcEJST0MzZkx0QTVBXzhkZw
      - FLEET_ENROLL=1
      #      - FLEET_SERVER_INSECURE_HTTP=true
      #      - FLEET_URL=https://fleet-server:8220
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=elastic123
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
  
  apm-server:
    image: docker.elastic.co/beats/elastic-agent:8.3.3
    hostname: apm-server
    container_name: apm-server
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
      - kibana
      - fleet-server
    networks:
      - elastic
    environment:
      - ENROLLMENT_TOKEN=cnFtaFk1QUJCMUljb3RCN3ZTMkg6Z3dlLWh4VHhTUnkzQkVnaUc5YkoyZw==
      - FLEET_ENROLL=1
      - FLEET_URL=https://fleet-server:8220
      - FLEET_INSECURE=true
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=elastic123
      - FLEET_TOKEN_POLICY_NAME=Agent policy Springboot

networks:
  elastic:
    driver: bridge

volumes:
  db:
  kibana_data:
  elasticsearch_data:
    driver: local
