http.host: 0.0.0.0
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.hosts: elasticsearch:9200
xpack.monitoring.elasticsearch.password: elastic123
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
